import { useState, useCallback, useRef, useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { useCompany, useSignals, useSnapshots, useContacts, useCompanyCards, useUpdateCompany, useMeetings, useCustomerActivity } from "@/hooks/useSupabase";
import { supabase } from "@/integrations/supabase/client";
import { useQueryClient } from "@tanstack/react-query";
import ScoreCell from "@/components/ScoreCell";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ArrowLeft, RefreshCw, ExternalLink, Briefcase, Newspaper, CheckCircle2, AlertCircle, Loader2, Target, TrendingUp, Shield, Zap, BarChart3, FileText, MessageSquareQuote, Eye, Building2, Users, DollarSign, ChevronRight, PhoneCall, UserSearch } from "lucide-react";
import { Json } from "@/integrations/supabase/types";
import { toast } from "sonner";

// Sub-components
import { parseJson, toArray, toLoomEmbedUrl, toIoradEmbedUrl } from "./company/types";
import type { SnapshotJSON, DashboardCard, EmailTouch, LinkedInStep, StoryAssets } from "./company/types";
import OnboardingTab from "./company/OnboardingTab";
import StrategyTab from "./company/StrategyTab";
import OutreachTab from "./company/OutreachTab";
import StoryTab from "./company/StoryTab";
import ContactsSection from "./company/ContactsSection";
import CompanySignalsSection from "./company/CompanySignalsSection";

export default function CompanyDetail() {
  const { id } = useParams<{ id: string }>();
  const { data: company, isLoading } = useCompany(id);
  const { data: signals = [] } = useSignals(id);
  const { data: snapshots = [] } = useSnapshots(id);
  const { data: contacts = [] } = useContacts(id);
  const { data: meetings = [] } = useMeetings(id);
  const { data: activityEvents = [] } = useCustomerActivity(id);
  const updateCompany = useUpdateCompany();
  const queryClient = useQueryClient();
  const [regenerating, setRegenerating] = useState(false);
  const [deleteContactId, setDeleteContactId] = useState<string | null>(null);
  const [deletingContact, setDeletingContact] = useState(false);
  const [setupRunning, setSetupRunning] = useState(false);
  const [setupStep, setSetupStep] = useState<string | null>(null);
  const [selectedContactId, setSelectedContactId] = useState<string>("");
  const [activeTab, setActiveTab] = useState("company");
  const [addContactOpen, setAddContactOpen] = useState(false);
  const [newContact, setNewContact] = useState({ name: "", title: "", email: "", linkedin: "" });
  const [savingContact, setSavingContact] = useState(false);
  const [loomUrl, setLoomUrl] = useState<string | null>(null);
  const [ioradUrl, setIoradUrl] = useState<string | null>(null);
  const [findingContacts, setFindingContacts] = useState(false);
  const [syncingFathom, setSyncingFathom] = useState(false);
  const [fixingDomain, setFixingDomain] = useState(false);
  const [analyzingMeeting, setAnalyzingMeeting] = useState<string | null>(null);
  const [contactSearch, setContactSearch] = useState("");
  const [syncingHubspot, setSyncingHubspot] = useState(false);
  const [generatingContactId, setGeneratingContactId] = useState<string | null>(null);
  const [regeneratingSection, setRegeneratingSection] = useState<string | null>(null);
  const [editingContactId, setEditingContactId] = useState<string | null>(null);
  const [editRoleFocus, setEditRoleFocus] = useState("");
  const [editUserNotes, setEditUserNotes] = useState("");
  // extractingProfiles state removed — extraction is now part of the generate pipeline

  // Auto-generate AI summary for creator contacts on load (every time contacts change)
  const autoGeneratedRef = useRef<Set<string>>(new Set());
  const setupRanRef = useRef(false);
  useEffect(() => {
    if (!id || contacts.length === 0) return;
    const creatorsWithoutProfile = contacts.filter((c: any) => {
      const hp = (c.hubspot_properties as any) || {};
      const isCreator = !!hp.first_tutorial_create_date;
      const hasProfile = !!(c as any).contact_profile?.account_narrative;
      return isCreator && !hasProfile && !autoGeneratedRef.current.has(c.id);
    });
    if (creatorsWithoutProfile.length === 0) return;

    // Mark all as queued so we don't re-trigger
    creatorsWithoutProfile.forEach((c: any) => autoGeneratedRef.current.add(c.id));

    const runExtraction = async () => {
      try {
        await supabase.functions.invoke("extract-contact-profile", { body: { company_id: id } });
        queryClient.invalidateQueries({ queryKey: ["contacts", id] });
      } catch (e) {
        console.warn("Auto profile extraction failed:", e);
      }
    };
    runExtraction();
  }, [id, contacts, queryClient]);

  const effectiveContactId = selectedContactId || contacts[0]?.id || "";
  const { data: companyCards, isLoading: cardsLoading } = useCompanyCards(id, effectiveContactId || undefined);

  const autosaveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const autosaveUrls = useCallback((loom: string, iorad: string) => {
    if (!id) return;
    if (autosaveTimer.current) clearTimeout(autosaveTimer.current);
    autosaveTimer.current = setTimeout(() => {
      updateCompany.mutate({ id, updates: { loom_url: loom || null, iorad_url: iorad || null } });
    }, 800);
  }, [id, updateCompany]);

  const companyAny = company as any;
  const companyCategory = companyAny?.category || (companyAny?.source_type === "inbound" ? "business" : companyAny?.partner ? "partner" : "business");
  const isPartnerCategory = companyCategory === "partner";
  const effectiveLoomUrl = loomUrl ?? companyAny?.loom_url ?? "";
  const effectiveIoradUrl = ioradUrl ?? companyAny?.iorad_url ?? "";

  const handleAddContact = async () => {
    if (!id || !newContact.name.trim()) return;
    setSavingContact(true);
    const missingContactInfo = !newContact.email.trim() || !newContact.linkedin.trim();
    try {
      // First insert the contact manually
      const { data: inserted, error } = await supabase.from("contacts").insert({
        company_id: id, name: newContact.name.trim(),
        title: newContact.title.trim() || null, email: newContact.email.trim() || null,
        linkedin: newContact.linkedin.trim() || null, source: "manual",
      }).select("id").single();
      if (error) throw error;

      // If email and linkedin are both blank, call Apollo to enrich
      if (missingContactInfo) {
        toast.info("Looking up contact details via Apollo…");
        try {
          const { data: apolloData, error: fnErr } = await supabase.functions.invoke("find-contacts", {
            body: { company_id: id, name_hint: newContact.name.trim() },
          });
          if (fnErr) throw fnErr;
          // Apollo may have saved a contact — check if it enriched the one we just inserted
          const { data: enriched } = await supabase
            .from("contacts")
            .select("email, linkedin")
            .eq("id", inserted.id)
            .maybeSingle();
          if (enriched?.email || enriched?.linkedin) {
            toast.success("Contact added and enriched via Apollo");
          } else {
            toast.success(`Contact added — Apollo found ${apolloData?.contacts_found ?? 0} related contacts`);
          }
        } catch {
          toast.success("Contact added (Apollo enrichment unavailable)");
        }
      } else {
        toast.success("Contact added");
      }

      setNewContact({ name: "", title: "", email: "", linkedin: "" });
      setAddContactOpen(false);
      queryClient.invalidateQueries({ queryKey: ["contacts", id] });
    } catch (e: any) { toast.error(e.message || "Failed to add contact"); }
    finally { setSavingContact(false); }
  };

  const handleDeleteContact = async (contactId: string) => {
    setDeletingContact(true);
    try {
      const { error } = await supabase.from("contacts").delete().eq("id", contactId);
      if (error) throw error;
      toast.success("Contact deleted");
      setDeleteContactId(null);
      queryClient.invalidateQueries({ queryKey: ["contacts", id] });
    } catch (e: any) { toast.error(e.message || "Failed to delete contact"); }
    finally { setDeletingContact(false); }
  };

  const regenerate = async (mode: string = "full") => {
    if (!id) return;
    setRegenerating(true);
    try {
      // Step 1: Run signals
      toast.info("Step 1/2 — Running signal search…");
      const { data, error } = await supabase.functions.invoke("run-signals", { body: { company_id: id, mode } });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      toast.success(`Signals complete — ${data?.signals_found ?? 0} found for ${data?.company || "company"}`);

      // Step 2: Sync Fathom meetings (if company has a domain)
      if (companyAny?.domain) {
        toast.info("Syncing Fathom meetings…");
        try {
          const { data: fData, error: fErr } = await supabase.functions.invoke("sync-fathom", {
            body: { domain: companyAny.domain, company_id: id },
          });
          if (!fErr && !fData?.error) {
            toast.success(`Fathom synced — ${fData?.meetings_synced ?? 0} meetings`);
            queryClient.invalidateQueries({ queryKey: ["meetings", id] });
          }
        } catch (fe: any) {
          console.warn("Fathom sync non-fatal:", fe.message);
        }
      }

      // Step 3: Find contacts via Apollo (skip for partner companies — contacts come from HubSpot)
      if (companyAny?.category === "partner" || (!companyAny?.category && companyAny?.source_type !== "inbound")) {
        toast.info("Step 3/3 — Finding contacts via Apollo…");
        setFindingContacts(true);
        try {
          const { data: contactData, error: contactErr } = await supabase.functions.invoke("find-contacts", { body: { company_id: id } });
          if (contactErr) throw contactErr;
          if (contactData?.error) throw new Error(contactData.error);
          if (contactData?.contacts_found > 0) {
            toast.success(`Found ${contactData.contacts_found} contacts via Apollo`);
          } else {
            toast.warning("No contacts found — check company domain is correct");
          }
        } catch (ce: any) {
          console.error("Contact enrichment failed:", ce);
          toast.error("Contact enrichment failed: " + (ce.message || "Unknown error"));
        } finally {
          setFindingContacts(false);
        }
      }

      // Step 3: For non-partner companies, extract contact profiles and generate company cards
      if (companyAny?.category !== "partner") {
        // Extract AI profiles from HubSpot data
        toast.info("Extracting contact profiles…");
        try {
          const { data: profileData, error: profileErr } = await supabase.functions.invoke("extract-contact-profile", { body: { company_id: id } });
          if (profileErr) console.warn("Profile extraction failed:", profileErr);
          else if (profileData?.profiles_extracted > 0) toast.success(`Extracted ${profileData.profiles_extracted} AI profiles`);
        } catch (pe: any) { console.warn("Profile extraction error:", pe.message); }

        // Generate company intel cards
        toast.info("Generating company intel…");
        try {
          const { data: cardData, error: cardErr } = await supabase.functions.invoke("generate-cards", { body: { company_id: id, tab: "company" } });
          if (cardErr) throw cardErr;
          if (cardData?.error) throw new Error(cardData.error);
          toast.success("Company intel generated");
        } catch (ce: any) {
          console.error("Card generation failed:", ce);
          toast.error("Card generation failed: " + (ce.message || "Unknown error"));
        }
      }

      queryClient.invalidateQueries({ queryKey: ["company", id] });
      queryClient.invalidateQueries({ queryKey: ["signals", id] });
      queryClient.invalidateQueries({ queryKey: ["snapshots", id] });
      queryClient.invalidateQueries({ queryKey: ["contacts", id] });
      // REFACTOR: (b) contact-scoped — prefix invalidation intentionally matches all ["company_cards", id, contactId] variants.
      queryClient.invalidateQueries({ queryKey: ["company_cards", id], exact: false });
      queryClient.invalidateQueries({ queryKey: ["companies"] });
    } catch (e: any) { toast.error(e.message || "Operation failed"); }
    finally { setRegenerating(false); }
  };

  const syncFathom = async () => {
    if (!company?.domain) { toast.error("Company needs a domain to sync Fathom meetings"); return; }
    setSyncingFathom(true);
    toast.info(`Syncing Fathom meetings for ${company.domain}…`);
    try {
      const { data, error } = await supabase.functions.invoke("sync-fathom", {
        body: { domain: company.domain, company_id: id },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      const synced = data.meetings_synced || 0;
      toast.success(`Synced ${synced} meetings`);
      await queryClient.invalidateQueries({ queryKey: ["meetings", id] });

      // Auto-analyze: get meetings with transcripts but no analysis yet
      if (synced > 0) {
        toast.info("Auto-analyzing transcripts…");
        const { data: freshMeetings } = await supabase
          .from("meetings")
          .select("id, transcript, transcript_analysis")
          .eq("company_id", id!)
          .not("transcript", "is", null)
          .is("transcript_analysis", null);

        if (freshMeetings && freshMeetings.length > 0) {
          for (const m of freshMeetings) {
            setAnalyzingMeeting(m.id);
            try {
              const { data: aData, error: aErr } = await supabase.functions.invoke("analyze-transcript", {
                body: { meeting_id: m.id },
              });
              if (aErr) throw aErr;
              if (aData?.error) throw new Error(aData.error);
            } catch (ae: any) {
              console.error(`Analysis failed for meeting ${m.id}:`, ae);
              toast.error(`Analysis failed for a meeting: ${ae.message}`);
            }
          }
          setAnalyzingMeeting(null);
          toast.success("Transcript analysis complete — check the Onboarding tab");
          queryClient.invalidateQueries({ queryKey: ["meetings", id] });
          setActiveTab("onboarding");
        }
      }
    } catch (e: any) { toast.error(e.message || "Fathom sync failed"); }
    finally { setSyncingFathom(false); setAnalyzingMeeting(null); }
  };

  const analyzeTranscript = async (meetingId: string) => {
    setAnalyzingMeeting(meetingId);
    toast.info("Analyzing transcript…");
    try {
      const { data, error } = await supabase.functions.invoke("analyze-transcript", {
        body: { meeting_id: meetingId },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      toast.success("Transcript analysis complete");
      queryClient.invalidateQueries({ queryKey: ["meetings", id] });
    } catch (e: any) { toast.error(e.message || "Analysis failed"); }
    finally { setAnalyzingMeeting(null); }
  };

  const fixDomain = async () => {
    if (!id) return;
    setFixingDomain(true);
    toast.info("AI is checking the domain…");
    try {
      const { data, error } = await supabase.functions.invoke("fix-domain", {
        body: { company_id: id },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      const result = data.results?.[0];
      if (result && result.old_domain !== result.new_domain) {
        toast.success(`Domain fixed: ${result.old_domain} → ${result.new_domain}`);
        queryClient.invalidateQueries({ queryKey: ["company", id] });
      } else {
        toast.info("Domain looks correct — no changes needed");
      }
    } catch (e: any) { toast.error(e.message || "Domain fix failed"); }
    finally { setFixingDomain(false); }
  };

  const runCompanySetup = async () => {
    if (!id || setupRunning || setupRanRef.current) return;
    setupRanRef.current = true;
    setSetupRunning(true);
    try {
      if (isPartnerCategory) {
        setSetupStep("Searching for signals…");
        try {
          await supabase.functions.invoke("run-signals", {
            body: { company_id: id, mode: "full" },
          });
          queryClient.invalidateQueries({ queryKey: ["signals", id] });
          queryClient.invalidateQueries({ queryKey: ["snapshots", id] });
        } catch (e: any) {
          console.warn("Signals non-fatal:", e.message);
        }
      }

      if (companyAny?.domain) {
        setSetupStep("Syncing meetings…");
        try {
          await supabase.functions.invoke("sync-fathom", {
            body: { domain: companyAny.domain, company_id: id },
          });
          queryClient.invalidateQueries({ queryKey: ["meetings", id] });
        } catch (e: any) {
          console.warn("Fathom non-fatal:", e.message);
        }
      }

      if (isPartnerCategory) {
        setSetupStep("Finding contacts…");
        try {
          await supabase.functions.invoke("find-contacts", { body: { company_id: id } });
          queryClient.invalidateQueries({ queryKey: ["contacts", id] });
        } catch (e: any) {
          console.warn("Contacts non-fatal:", e.message);
        }
      }

      setSetupStep("Analyzing company…");
      try {
        await supabase.functions.invoke("generate-cards", {
          body: { company_id: id, tab: "company" },
        });
        queryClient.invalidateQueries({ queryKey: ["company_cards", id], exact: false });
      } catch (e: any) {
        console.warn("Company intel non-fatal:", e.message);
      }

      if (companyAny?.domain) {
        try {
          const { data: freshMeetings } = await supabase
            .from("meetings")
            .select("id, transcript, transcript_analysis")
            .eq("company_id", id)
            .not("transcript", "is", null)
            .is("transcript_analysis", null);
          if (freshMeetings && freshMeetings.length > 0) {
            setSetupStep("Analyzing transcripts…");
            for (const m of freshMeetings) {
              try {
                await supabase.functions.invoke("analyze-transcript", { body: { meeting_id: m.id } });
              } catch {}
            }
            queryClient.invalidateQueries({ queryKey: ["meetings", id] });
          }
        } catch {}
      }

      setSetupStep("Building contact profiles…");
      try {
        await supabase.functions.invoke("extract-contact-profile", { body: { company_id: id } });
        queryClient.invalidateQueries({ queryKey: ["contacts", id] });
      } catch (e: any) {
        console.warn("Profile extraction non-fatal:", e.message);
      }

      await updateCompany.mutateAsync({
        id: id!,
        updates: { last_processed_at: new Date().toISOString() },
      });
      queryClient.invalidateQueries({ queryKey: ["company", id] });
    } catch (e: any) {
      console.error("Company setup failed:", e.message);
      toast.error("Setup failed — try refreshing");
      setupRanRef.current = false;
    } finally {
      setSetupRunning(false);
      setSetupStep(null);
    }
  };

  useEffect(() => {
    if (!company || isLoading) return;
    const needsSetup = !companyAny?.last_processed_at;
    if (needsSetup && !setupRunning && !setupRanRef.current) {
      runCompanySetup();
    }
  }, [company, isLoading]);

  const syncHubspot = async () => {
    if (!id) return;
    setSyncingHubspot(true);
    try {
      toast.info("Syncing HubSpot data…");
      const { data, error } = await supabase.functions.invoke("import-from-hubspot", {
        body: { action: "sync_company", domain: (company as any)?.domain, company_id: id },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      toast.success(
        data?.is_existing_customer
          ? "HubSpot synced — flagged as existing customer"
          : `HubSpot synced — ${data?.contacts_imported ?? 0} contact(s) updated`
      );
      queryClient.invalidateQueries({ queryKey: ["company", id] });
      queryClient.invalidateQueries({ queryKey: ["contacts", id] });
    } catch (e: any) { toast.error(e.message || "HubSpot sync failed"); }
    finally { setSyncingHubspot(false); }
  };

  const generateForContact = async (contactId: string) => {
    if (!id) return;
    setGeneratingContactId(contactId);
    try {
      // Step 1: Extract profile for this contact
      toast.info("Extracting contact profile…");
      try {
        await supabase.functions.invoke("extract-contact-profile", { body: { company_id: id, contact_id: contactId } });
        queryClient.invalidateQueries({ queryKey: ["contacts", id] });
      } catch (pe: any) { console.warn("Profile extraction non-fatal:", pe.message); }

      // Step 2: Generate contact-scoped tabs for this contact (in parallel)
      toast.info("Generating contact content…");

      const contactTabs = ["strategy", "outreach", "story"];
      const results = await Promise.allSettled(
        contactTabs.map((tab) =>
          supabase.functions.invoke("generate-cards", {
            body: { company_id: id, tab, contact_id: contactId },
          })
        )
      );

      const failures = results
        .map((result, i) => ({ result, tab: contactTabs[i] }))
        .filter(
          (r) =>
            r.result.status === "rejected" ||
            (r.result.status === "fulfilled" && (r.result.value.error || r.result.value.data?.error))
        );

      if (failures.length > 0) {
        const failedTabs = failures.map((f) => f.tab).join(", ");
        toast.warning(`Some tabs failed: ${failedTabs}. Others succeeded.`);
      }

      const firstName = contacts.find((c: any) => c.id === contactId)?.name?.split(" ")[0] || "contact";
      const slug = firstName.toLowerCase().replace(/[^a-z]/g, "");
      const storyUrl = !isPartnerCategory
        ? `/stories/${companyNameSlug}/${slug}`
        : company.partner
          ? `/${company.partner}/${companyNameSlug}/stories/${slug}`
          : null;
      toast.success(`Content generated for ${firstName}`, {
        action: storyUrl ? {
          label: "View Story →",
          onClick: () => window.open(storyUrl, "_blank"),
        } : undefined,
        duration: 8000,
      });
      // REFACTOR: (b) contact-scoped — prefix invalidation intentionally matches all ["company_cards", id, contactId] variants.
      queryClient.invalidateQueries({ queryKey: ["company_cards", id], exact: false });
      queryClient.invalidateQueries({ queryKey: ["contacts", id] });
      // Switch to this contact
      setSelectedContactId(contactId);
    } catch (e: any) { toast.error(e.message || "Generation failed"); }
    finally { setGeneratingContactId(null); }
  };

  if (isLoading) {
    return <div className="flex items-center justify-center py-20"><Loader2 className="w-6 h-6 animate-spin text-primary" /></div>;
  }

  if (!company) {
    return (
      <div className="text-center py-20">
        <h2 className="text-xl font-bold">Company not found</h2>
        <Link to="/" className="text-primary text-sm mt-2 inline-block">← Back to Dashboard</Link>
      </div>
    );
  }

  const latestSnapshot = snapshots[0];
  const snap = latestSnapshot ? parseJson<SnapshotJSON>(latestSnapshot.snapshot_json) : null;

  const cards = (companyCards?.cards_json as unknown as DashboardCard[] | null) || [];
  const assets = parseJson<{ email_sequence?: Record<string, EmailTouch>; linkedin_sequence?: LinkedInStep[]; story_assets?: StoryAssets }>(companyCards?.assets_json as Json) || {};
  const rawAccountJson = parseJson<Record<string, unknown>>(companyCards?.account_json as Json) || {};
  // Strategy data: check dedicated _strategy namespace first, then fall back to root-level fields
  // (root-level exists when data was generated before the namespacing fix)
  const inboundStrategyData: Record<string, unknown> | null = (() => {
    const namespaced = rawAccountJson?._strategy as Record<string, unknown> | undefined;
    if (namespaced && (namespaced.momentum_observed || namespaced.initiative_translation || namespaced.opening_paragraph || namespaced.subject_line || namespaced.observed_behavior)) {
      return namespaced;
    }
    // Fallback: root-level fields (legacy data)
    if (rawAccountJson?.momentum_observed || rawAccountJson?.initiative_translation || rawAccountJson?.opening_paragraph || rawAccountJson?.subject_line) {
      return rawAccountJson;
    }
    return null;
  })();
  const isInboundStrategyResponse = !!(inboundStrategyData?.momentum_observed || inboundStrategyData?.initiative_translation || inboundStrategyData?.observed_behavior || inboundStrategyData?.subject_line || inboundStrategyData?.opening_paragraph);
  // Story data is stored at root with _type: inbound_story
  const isInboundStoryResponse = !!(rawAccountJson?._type === "inbound_story" || rawAccountJson?.behavior_acknowledged);
  const inboundStrategyFields: { label: string; key: string }[] = [
    { label: "Momentum Observed", key: "momentum_observed" },
    { label: "Initiative Translation", key: "initiative_translation" },
    { label: "Scale Risk", key: "scale_risk" },
    { label: "Institutionalization Gap", key: "institutionalization_gap" },
    { label: "Executive Translation", key: "executive_translation" },
    { label: "Real Cost If Stalled", key: "real_cost_if_stalled" },
    { label: "Upside If Executed", key: "upside_if_executed" },
    { label: "Why Now", key: "why_now" },
    // Legacy fields (old prompt format)
    { label: "Observed Behavior", key: "observed_behavior" },
    { label: "Inferred Initiative", key: "inferred_initiative" },
    { label: "Execution Gap", key: "execution_gap" },
    { label: "Institutionalization Play", key: "institutionalization_play" },
    { label: "ROI Expansion Path", key: "roi_expansion_path" },
  ];
  const accountData = parseJson<{
    name?: string; about?: { text?: string; status?: string };
    industry?: { value?: string; status?: string };
    employees?: { value?: string; status?: string };
    hq?: { value?: string; status?: string };
    revenue_range?: { value?: string; status?: string };
    products_services?: { name: string; status?: string }[];
  }>(companyCards?.account_json as Json);

  const loomEmbedUrl = toLoomEmbedUrl(effectiveLoomUrl);
  const ioradEmbedUrl = toIoradEmbedUrl(effectiveIoradUrl);

  const activeContact = contacts.find((c: any) => c.id === effectiveContactId)
    || contacts[0]
    || (companyAny?.buyer_name ? { name: companyAny.buyer_name } : null);
  const activeContactName = activeContact?.name?.split(" ")[0] || null;
  // category determines story URL type: non-partner (school/business) uses company_cards.id; partner uses slug
  const companyStage = companyAny?.stage || "prospect";
  const companyNameSlug = company.name.toLowerCase().replace(/\s+/g, "-");
  const contactSlug = activeContact ? activeContact.name.split(" ")[0].toLowerCase().replace(/[^a-z]/g, "") : null;
  const storyBaseUrl = !isPartnerCategory
    ? contactSlug ? `/stories/${companyNameSlug}/${contactSlug}` : `/stories/${companyNameSlug}`
    : activeContact && company.partner
      ? `/${company.partner}/${companyNameSlug}/stories/${activeContact.name.split(" ")[0].toLowerCase().replace(/[^a-z]/g, "")}`
      : null;

  // Small ghost regen button for individual sections
  const RegenerateBtn = ({ section, label }: { section: Parameters<typeof regenerateSection>[0]; label: string }) => (
    <Button
      size="sm"
      variant="ghost"
      className="h-6 gap-1 text-micro text-foreground/45 hover:text-foreground px-2"
      disabled={regeneratingSection === section || setupRunning}
      onClick={() => regenerateSection(section)}
    >
      {regeneratingSection === section
        ? <Loader2 className="w-3 h-3 animate-spin" />
        : <RefreshCw className="w-3 h-3" />}
      {label}
    </Button>
  );

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
      <div className="flex items-center gap-4">
          <Link to="/" className="text-foreground/45 hover:text-foreground transition-colors"><ArrowLeft className="w-5 h-5" /></Link>
          <div>
            <div className="flex items-center gap-3">
              <h1 className="text-display font-bold tracking-tight leading-tight">{company.name}</h1>
              {company.scout_score !== null && company.scout_score !== undefined && (
                <ScoreCell score={company.scout_score} size="lg" />
              )}
            </div>
            <p className="text-caption text-foreground/45 mt-0.5">{company.domain || "no domain"}</p>
            {company.scout_summary && (
              <p className="text-caption text-foreground/45 mt-1 max-w-xl leading-relaxed italic">{company.scout_summary}</p>
            )}
          </div>
        </div>
        {/* Category + Stage inline selectors */}
        <div className="flex items-center gap-2 flex-wrap">
          <Select
            value={companyCategory}
            onValueChange={async (val) => {
              await updateCompany.mutateAsync({ id: id!, updates: { category: val } as any });
              queryClient.invalidateQueries({ queryKey: ["company", id] });
            }}
          >
            <SelectTrigger className="h-7 text-xs w-[130px] bg-secondary border-0">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="school">School (EDU)</SelectItem>
              <SelectItem value="business">Business (B2B)</SelectItem>
              <SelectItem value="partner">Partner</SelectItem>
            </SelectContent>
          </Select>
          <Select
            value={companyStage}
            onValueChange={async (val) => {
              await updateCompany.mutateAsync({ id: id!, updates: { stage: val } as any });
              queryClient.invalidateQueries({ queryKey: ["company", id] });
            }}
          >
            <SelectTrigger className="h-7 text-xs w-[130px] bg-secondary border-0">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="prospect">Prospect</SelectItem>
              <SelectItem value="active_opp">Active Opp</SelectItem>
              <SelectItem value="customer">Customer</SelectItem>
              <SelectItem value="expansion">Expansion</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      {setupRunning && (
        <div className="flex items-center gap-3 px-4 py-3 rounded-lg bg-primary/[0.06] border border-primary/10">
          <Loader2 className="w-4 h-4 animate-spin text-primary flex-shrink-0" />
          <div>
            <div className="text-body font-medium text-foreground">Setting up {company.name}…</div>
            {setupStep && <div className="text-caption text-foreground/45 mt-0.5">{setupStep}</div>}
          </div>
        </div>
      )}

      {contacts.length > 0 && (
        <div className="flex items-center gap-3 px-3 py-2 rounded-lg bg-secondary/30 border border-border/40">
          <div className="flex items-center gap-2 text-caption text-foreground/45">
            <UserSearch className="w-3.5 h-3.5" />
            <span className="font-medium">Contact</span>
          </div>
          <Select value={selectedContactId || contacts[0]?.id || ""} onValueChange={setSelectedContactId}>
            <SelectTrigger className="h-8 min-w-[220px] max-w-[320px] py-1 px-3 text-xs bg-background border-border/30">
              <SelectValue placeholder="Select contact">
                {(() => {
                  const c = contacts.find((c: any) => c.id === effectiveContactId);
                  if (!c) return null;
                  return (
                    <div className="flex items-center gap-2">
                      <span className="font-medium text-caption">{c.name}</span>
                      {c.title && <span className="text-foreground/45 text-micro">· {c.title}</span>}
                    </div>
                  );
                })()}
              </SelectValue>
            </SelectTrigger>
            <SelectContent className="bg-background z-50 min-w-[280px]">
              {contacts.map((c: any) => (
                <SelectItem key={c.id} value={c.id} className="py-2">
                  <div className="flex flex-col items-start">
                    <span className="font-medium text-caption leading-tight">{c.name}</span>
                    {c.title && <span className="text-foreground/45 text-micro leading-tight">{c.title}</span>}
                    {(c as any).role_focus && <span className="text-primary/70 text-micro leading-tight">{(c as any).role_focus}</span>}
                  </div>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <span className="text-micro text-foreground/25 ml-auto">
            Strategy, Outreach & Story are generated for this contact
          </span>
        </div>
      )}

      <Tabs defaultValue="company" className="w-full" onValueChange={setActiveTab}>
        <div className="flex items-center justify-between gap-3 mb-4">
          <TabsList className="justify-start gap-0">
            <TabsTrigger value="company" className="text-sm">Company</TabsTrigger>
            <TabsTrigger value="onboarding" className="text-sm">Onboarding</TabsTrigger>
            <div className="w-px h-5 bg-border/60 mx-1.5" />
            <TabsTrigger value="strategy" className="text-sm">Strategy</TabsTrigger>
            <TabsTrigger value="outreach" className="text-sm">Outreach</TabsTrigger>
            <TabsTrigger value="story" className="text-sm">Story</TabsTrigger>
          </TabsList>

          {/* Tab action bar */}
          {activeTab === "company" || activeTab === "onboarding" ? (
            <Button
              size="sm"
              variant="outline"
              className="gap-1.5 text-caption"
              onClick={() => { setupRanRef.current = false; runCompanySetup(); }}
              disabled={setupRunning}
            >
              {setupRunning
                ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
                : <RefreshCw className="w-3.5 h-3.5" />}
              {setupRunning ? (setupStep || "Setting up…") : "Refresh Company Data"}
            </Button>
          ) : (
            <div className="flex items-center gap-2">
              {storyBaseUrl && (
                <a href={storyBaseUrl} target="_blank" rel="noopener noreferrer">
                  <Button size="sm" variant="outline" className="gap-1.5 text-caption">
                    <Eye className="w-3.5 h-3.5" /> View Story
                  </Button>
                </a>
              )}
            </div>
          )}
        </div>

        {/* ============ TAB 1: COMPANY ============ */}
        <TabsContent value="company" className="space-y-8 mt-6">
          <div className="flex items-center justify-between">
            <h3 className="section-label">Company Intel</h3>
            <div className="flex items-center gap-1">
              <Button
                variant="outline"
                size="sm"
                className="h-7 px-2.5 text-xs gap-1.5"
                onClick={syncHubspot}
                disabled={syncingHubspot}
                title="Sync contacts and customer status from HubSpot"
              >
                {syncingHubspot ? <Loader2 className="w-3 h-3 animate-spin" /> : <RefreshCw className="w-3 h-3" />}
                HubSpot Sync
              </Button>
              {companyAny?.source_type !== "inbound" && <RegenerateBtn section="signals" label="Signals" />}
              <RegenerateBtn section="company" label="Company Intel" />
            </div>
          </div>

          {/* Company Profile */}
          {accountData?.about?.text && (
            <p className="text-body text-foreground/65 leading-relaxed line-clamp-2">
              {accountData.about.text}
            </p>
          )}
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
            {(accountData?.industry?.value || company.industry) && (
              <Card className="bg-secondary/30"><CardContent className="p-4 flex flex-col items-start gap-1.5">
                <Building2 className="w-4 h-4 text-primary" />
                <span className="section-label">Industry</span>
                <span className="text-caption font-medium text-foreground leading-tight">{accountData?.industry?.value || company.industry?.replace(/_/g, " ").toLowerCase()}</span>
              </CardContent></Card>
            )}
            {(accountData?.employees?.value || company.headcount) && (
              <Card className="bg-secondary/30"><CardContent className="p-4 flex flex-col items-start gap-1.5">
                <Users className="w-4 h-4 text-primary" />
                <span className="section-label">Employees</span>
                <span className="text-caption font-medium text-foreground">{accountData?.employees?.value || `${company.headcount}+`}</span>
              </CardContent></Card>
            )}
            {accountData?.revenue_range?.value && accountData.revenue_range.value !== "Unknown" && (
              <Card className="bg-secondary/30"><CardContent className="p-4 flex flex-col items-start gap-1.5">
                <DollarSign className="w-4 h-4 text-primary" />
                <span className="section-label">Revenue</span>
                <span className="text-caption font-medium text-foreground">{accountData.revenue_range.value}</span>
              </CardContent></Card>
            )}
            {company.partner && (
              <Card className="bg-secondary/30"><CardContent className="p-4 flex flex-col items-start gap-1.5">
                <Briefcase className="w-4 h-4 text-primary" />
                <span className="section-label">Partner</span>
                <span className="text-caption font-medium text-foreground">{company.partner}</span>
              </CardContent></Card>
            )}
          </div>

          {/* HubSpot Product Properties */}
          {companyAny?.hubspot_properties && Object.keys(companyAny.hubspot_properties).length > 0 && (
            <Collapsible>
              <CollapsibleTrigger className="flex items-center gap-2 w-full text-left">
                <ChevronRight className="w-4 h-4 text-foreground/45 transition-transform data-[state=open]:rotate-90" />
                <span className="section-label">iorad Product Data (HubSpot)</span>
                <Badge variant="outline" className="text-micro h-4 ml-auto">
                  {Object.entries(companyAny.hubspot_properties).filter(([_, v]) => v !== null && v !== "" && v !== undefined).length} properties
                </Badge>
              </CollapsibleTrigger>
              <CollapsibleContent className="mt-3">
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2">
                  {Object.entries(companyAny.hubspot_properties as Record<string, any>)
                    .filter(([_, v]) => v !== null && v !== "" && v !== undefined)
                    .filter(([k]) => !["name", "domain", "industry", "country", "numberofemployees", "hs_object_id", "createdate", "hs_lastmodifieddate", "hs_pipeline"].includes(k))
                    .sort(([a], [b]) => a.localeCompare(b))
                    .map(([key, value]) => (
                       <div key={key} className="px-3 py-2 rounded-lg border border-border/30 bg-secondary/20">
                        <div className="section-label truncate" title={key}>
                          {key.replace(/_/g, " ").replace(/^hs /, "")}
                        </div>
                        <div className="text-caption font-medium text-foreground mt-0.5 truncate" title={String(value)}>
                          {String(value).length > 80 ? String(value).slice(0, 80) + "…" : String(value)}
                        </div>
                      </div>
                    ))}
                </div>
              </CollapsibleContent>
            </Collapsible>
          )}

          <ContactsSection
            companyId={id!}
            contacts={contacts}
            snapshots={snapshots}
            company={company}
            isPartnerCategory={isPartnerCategory}
            companyNameSlug={companyNameSlug}
            findingContacts={findingContacts}
            generatingContactId={generatingContactId}
            editingContactId={editingContactId}
            editRoleFocus={editRoleFocus}
            editUserNotes={editUserNotes}
            onSetEditingContactId={setEditingContactId}
            onSetEditRoleFocus={setEditRoleFocus}
            onSetEditUserNotes={setEditUserNotes}
            onGenerateForContact={generateForContact}
            onDeleteContact={(cid) => setDeleteContactId(cid)}
            addContactOpen={addContactOpen}
            onSetAddContactOpen={setAddContactOpen}
            newContact={newContact}
            onSetNewContact={setNewContact}
            onAddContact={handleAddContact}
            savingContact={savingContact}
            contactSearch={contactSearch}
            onSetContactSearch={setContactSearch}
            onRegenerateContacts={() => regenerateSection("contacts")}
            regeneratingSection={regeneratingSection}
            setupRunning={setupRunning}
            deleteContactId={deleteContactId}
            onSetDeleteContactId={setDeleteContactId}
            deletingContact={deletingContact}
            onConfirmDelete={() => deleteContactId && handleDeleteContact(deleteContactId)}
          />

          {/* Meetings (Fathom) */}
          <Card className="bg-secondary/30">
            <CardContent className="p-4 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-primary/10">
                  <PhoneCall className="w-4 h-4 text-primary" />
                </div>
                <div>
                  <div className="text-body font-medium text-foreground">
                    {meetings.length} Meeting{meetings.length !== 1 ? "s" : ""} Synced
                  </div>
                  <div className="text-caption text-foreground/45">
                    {meetings.filter((m: any) => m.transcript_analysis).length} analyzed
                    {(syncingFathom || analyzingMeeting) && (
                      <span className="ml-2 inline-flex items-center gap-1">
                        <Loader2 className="w-3 h-3 animate-spin" />
                        {syncingFathom ? "Syncing…" : "Analyzing…"}
                      </span>
                    )}
                  </div>
                </div>
              </div>
              <Button size="sm" variant="outline" className="gap-1.5 text-caption" onClick={syncFathom} disabled={syncingFathom || !!analyzingMeeting}>
                {syncingFathom ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <RefreshCw className="w-3.5 h-3.5" />}
                Sync Fathom
              </Button>
            </CardContent>
          </Card>

          {snap && latestSnapshot && (
            <div className="panel">
              <div className="panel-header flex items-center justify-between">
                <span>iorad Expansion Analysis</span>
                <span className="text-micro text-foreground/45 normal-case tracking-normal">
                  {latestSnapshot.model_version} · {latestSnapshot.prompt_version} · {new Date(latestSnapshot.created_at).toLocaleDateString()}
                </span>
              </div>

              {snap.why_now && toArray(snap.why_now).length > 0 && (
                <div className="mb-4 bg-primary/5 border border-primary/20 rounded-lg p-4">
                  <div className="section-label text-primary mb-2">Why Now</div>
                  {toArray(snap.why_now).map((item, i) => <p key={i} className="text-body text-foreground/65 leading-relaxed">{item}</p>)}
                </div>
              )}

              <Accordion type="multiple" defaultValue={["executive-narrative"]} className="space-y-2">
                {snap.signal_deconstruction && (
                  <AccordionItem value="signal-deconstruction" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><Target className="w-4 h-4 text-primary" /> Signal Deconstruction</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <div className="space-y-4">
                        {snap.signal_deconstruction.company_stage && (
                          <div>
                            <div className="text-micro text-foreground/45 mb-1">Company Stage</div>
                            <span className="text-sm bg-primary/10 text-primary px-2 py-0.5 rounded">{snap.signal_deconstruction.company_stage}</span>
                          </div>
                        )}
                        {snap.signal_deconstruction.observable_facts?.length ? (
                          <div>
                            <div className="text-micro text-foreground/45 mb-2">Observable Facts</div>
                            <ul className="space-y-1">{snap.signal_deconstruction.observable_facts.map((f, i) => <li key={i} className="text-sm flex items-start gap-2"><span className="text-primary">•</span>{f}</li>)}</ul>
                          </div>
                        ) : null}
                        {snap.signal_deconstruction.workflow_stress_indicators?.length ? (
                          <div>
                            <div className="text-micro text-foreground/45 mb-2">Workflow Stress Indicators</div>
                            <ul className="space-y-1">{snap.signal_deconstruction.workflow_stress_indicators.map((w, i) => <li key={i} className="text-sm flex items-start gap-2"><AlertCircle className="w-3.5 h-3.5 text-destructive mt-0.5 flex-shrink-0" />{w}</li>)}</ul>
                          </div>
                        ) : null}
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                )}

                {snap.operational_friction?.length ? (
                  <AccordionItem value="operational-friction" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><Zap className="w-4 h-4 text-primary" /> Operational Friction</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <div className="space-y-3">
                        {snap.operational_friction.map((f, i) => (
                          <div key={i} className="bg-secondary/50 rounded-lg p-4 space-y-1">
                            <div className="text-body"><span className="font-medium text-foreground">Cause:</span> <span className="text-foreground/65">{f.cause}</span></div>
                            <div className="text-body"><span className="font-medium text-foreground">→ Effect:</span> <span className="text-foreground/65">{f.effect}</span></div>
                            <div className="text-body"><span className="font-medium text-foreground">→ Bottleneck:</span> <span className="text-foreground/65">{f.bottleneck}</span></div>
                          </div>
                        ))}
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                ) : null}

                {snap.partner_platform_ceiling && (
                  <AccordionItem value="partner-ceiling" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><TrendingUp className="w-4 h-4 text-primary" /> Partner Platform Ceiling</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <div className="space-y-4">
                        {snap.partner_platform_ceiling.platform_strengths?.length ? (
                          <div>
                            <div className="text-micro text-foreground/45 mb-2">Platform Strengths</div>
                            <div className="flex flex-wrap gap-1.5">{snap.partner_platform_ceiling.platform_strengths.map((s, i) => <span key={i} className="text-xs bg-primary/10 text-primary px-2 py-0.5 rounded">{s}</span>)}</div>
                          </div>
                        ) : null}
                        {snap.partner_platform_ceiling.execution_gaps?.length ? (
                          <div>
                            <div className="text-micro text-foreground/45 mb-2">Execution Gaps</div>
                            <ul className="space-y-1">{snap.partner_platform_ceiling.execution_gaps.map((g, i) => <li key={i} className="text-sm flex items-start gap-2"><span className="text-destructive">✕</span>{g}</li>)}</ul>
                          </div>
                        ) : null}
                        {snap.partner_platform_ceiling.key_insight && (
                          <div className="bg-primary/5 border border-primary/20 rounded p-4 text-body italic text-foreground/65">{snap.partner_platform_ceiling.key_insight}</div>
                        )}
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                )}

                {snap.embedded_leverage && (
                  <AccordionItem value="embedded-leverage" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><Zap className="w-4 h-4 text-primary" /> Embedded iorad Leverage</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        {(["situation", "constraint", "intervention", "transformation"] as const).map(key => {
                          const val = snap.embedded_leverage?.[key];
                          if (!val) return null;
                          const labels: Record<string, string> = { situation: "Situation", constraint: "Constraint", intervention: "Intervention", transformation: "Transformation" };
                          return (
                            <div key={key} className="bg-secondary/50 rounded-lg p-4">
                              <div className="text-micro text-foreground/45 mb-1">{labels[key]}</div>
                              <p className="text-sm text-foreground/90">{val}</p>
                            </div>
                          );
                        })}
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                )}

                {snap.quantified_impact?.length ? (
                  <AccordionItem value="quantified-impact" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><BarChart3 className="w-4 h-4 text-primary" /> Quantified Impact</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <div className="space-y-3">
                        {snap.quantified_impact.map((q, i) => (
                          <div key={i} className="border rounded-lg p-4 space-y-2">
                            <div className="font-medium text-sm text-foreground">{q.metric}</div>
                            <div className="text-micro text-foreground/45"><span className="font-mono">Assumptions:</span> {q.assumptions}</div>
                            <div className="text-xs font-mono bg-secondary/50 rounded p-2 text-foreground/80">{q.calculation}</div>
                            <div className="text-sm font-bold text-primary">{q.result}</div>
                          </div>
                        ))}
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                ) : null}

                {snap.executive_narrative && (
                  <AccordionItem value="executive-narrative" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><FileText className="w-4 h-4 text-primary" /> Executive Narrative</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <div className="prose prose-sm dark:prose-invert max-w-none">
                        {(Array.isArray(snap.executive_narrative)
                          ? snap.executive_narrative
                          : typeof snap.executive_narrative === 'string' ? snap.executive_narrative.split("\n\n") : []
                        ).map((p: string, i: number) => (
                          <p key={i} className="text-body text-foreground/65 leading-relaxed mb-4">{p}</p>
                        ))}
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                )}

                {snap.outbound_positioning && (
                  <AccordionItem value="outbound-positioning" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><MessageSquareQuote className="w-4 h-4 text-primary" /> Outbound Positioning</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <div className="space-y-3">
                        {snap.outbound_positioning.executive_framing && (
                          <div className="border-l border-primary/20 pl-3">
                            <div className="text-micro text-foreground/45 mb-1">Executive Framing</div>
                            <p className="text-sm text-foreground/90 italic">"{snap.outbound_positioning.executive_framing}"</p>
                          </div>
                        )}
                        {snap.outbound_positioning.efficiency_framing && (
                          <div className="border-l border-primary/20 pl-3">
                            <div className="text-micro text-foreground/45 mb-1">Efficiency / Revenue</div>
                            <p className="text-sm text-foreground/90 italic">"{snap.outbound_positioning.efficiency_framing}"</p>
                          </div>
                        )}
                        {snap.outbound_positioning.risk_framing && (
                          <div className="border-l border-primary/20 pl-3">
                            <div className="text-micro text-foreground/45 mb-1">Risk Mitigation</div>
                            <p className="text-sm text-foreground/90 italic">"{snap.outbound_positioning.risk_framing}"</p>
                          </div>
                        )}
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                )}

                {snap.competitive_insulation?.length ? (
                  <AccordionItem value="competitive-insulation" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><Shield className="w-4 h-4 text-primary" /> Competitive Insulation</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <ul className="space-y-1.5">{snap.competitive_insulation.map((r, i) => <li key={i} className="text-sm flex items-start gap-2"><CheckCircle2 className="w-3.5 h-3.5 text-primary mt-0.5 flex-shrink-0" />{r}</li>)}</ul>
                    </AccordionContent>
                  </AccordionItem>
                ) : null}

                {snap.evidence?.length ? (
                  <AccordionItem value="evidence" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><ExternalLink className="w-4 h-4 text-primary" /> Cited Evidence ({snap.evidence.length})</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <div className="space-y-2">
                        {snap.evidence.map((ev, i) => (
                          <div key={i} className="text-xs border-l border-primary/20 pl-3 py-1">
                            <p className="text-foreground/65 italic">"{ev.snippet || ev.detail || ""}"</p>
                            <a href={ev.source_url || ev.url || "#"} target="_blank" rel="noopener noreferrer" className="text-primary hover:underline flex items-center gap-1 mt-0.5">
                              <ExternalLink className="w-3 h-3" /> {ev.source_type || ev.signal_type || "source"} · {ev.date || "no date"}
                            </a>
                          </div>
                        ))}
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                ) : null}
              </Accordion>
            </div>
          )}

          <div className="glow-line" />

          <CompanySignalsSection
            signals={signals}
            snapshots={snapshots}
            activityEvents={activityEvents}
            meetings={meetings}
            company={company}
          />
        </TabsContent>

        {/* ============ TAB 2: ONBOARDING ============ */}
        <TabsContent value="onboarding">
          <OnboardingTab
            meetings={meetings}
            analyzingMeeting={analyzingMeeting}
            onAnalyze={analyzeTranscript}
          />
        </TabsContent>

        {/* ============ TAB 3: STRATEGY ============ */}
        <TabsContent value="strategy" className="space-y-8 mt-6">
          <StrategyTab
            contactName={activeContactName}
            cardsLoading={cardsLoading}
            isInboundStrategyResponse={isInboundStrategyResponse}
            inboundStrategyData={inboundStrategyData}
            inboundStrategyFields={inboundStrategyFields}
            cards={cards}
            regeneratingSection={regeneratingSection}
            setupRunning={setupRunning}
            onRegenerate={() => regenerateSection("strategy")}
          />
        </TabsContent>

        {/* ============ TAB 4: OUTREACH ============ */}
        <TabsContent value="outreach" className="space-y-8 mt-6">
          <OutreachTab
            contactName={activeContactName}
            cardsLoading={cardsLoading}
            rawAccountJson={rawAccountJson}
            emailSequence={assets.email_sequence}
            linkedinSequence={assets.linkedin_sequence}
            regeneratingSection={regeneratingSection}
            setupRunning={setupRunning}
            onRegenerate={() => regenerateSection("outreach")}
          />
        </TabsContent>

        {/* ============ TAB 5: STORY ============ */}
        <TabsContent value="story" className="space-y-8 mt-6">
          <StoryTab
            contactName={activeContactName}
            isInboundStoryResponse={isInboundStoryResponse}
            rawAccountJson={rawAccountJson}
            storyBaseUrl={storyBaseUrl}
            loomUrl={effectiveLoomUrl}
            ioradUrl={effectiveIoradUrl}
            loomEmbedUrl={loomEmbedUrl}
            ioradEmbedUrl={ioradEmbedUrl}
            onLoomUrlChange={(v) => { setLoomUrl(v); autosaveUrls(v, effectiveIoradUrl); }}
            onIoradUrlChange={(v) => { setIoradUrl(v); autosaveUrls(effectiveLoomUrl, v); }}
            regeneratingSection={regeneratingSection}
            setupRunning={setupRunning}
            onRegenerate={() => regenerateSection("story")}
          />
        </TabsContent>

      </Tabs>
    </div>
  );
}
