import { useState, useCallback, useRef, useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { useCompany, useSignals, useSnapshots, useContacts, useCompanyCards, useUpdateCompany, useMeetings, useCustomerActivity } from "@/hooks/useSupabase";
import { supabase } from "@/integrations/supabase/client";
import { useQueryClient } from "@tanstack/react-query";
import ScoreCell from "@/components/ScoreCell";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ArrowLeft, RefreshCw, ExternalLink, Newspaper, CheckCircle2, AlertCircle, Loader2, Target, TrendingUp, Shield, Zap, BarChart3, FileText, MessageSquareQuote, ChevronRight } from "lucide-react";
import { Json } from "@/integrations/supabase/types";
import { toast } from "sonner";

// Sub-components
import { parseJson, toArray } from "./company/types";
import type { SnapshotJSON } from "./company/types";
import OnboardingTab from "./company/OnboardingTab";
import CompanySignalsSection from "./company/CompanySignalsSection";
import ContactDetailView from "./company/ContactDetailView";

export default function CompanyDetail() {
  const { id } = useParams<{ id: string }>();
  const { data: company, isLoading } = useCompany(id);
  const { data: signals = [] } = useSignals(id);
  const { data: snapshots = [] } = useSnapshots(id);
  const { data: contacts = [] } = useContacts(id);
  const { data: meetings = [] } = useMeetings(id);
  const { data: activityEvents = [] } = useCustomerActivity(id);
  const updateCompany = useUpdateCompany();
  const queryClient = useQueryClient();
  const [regenerating, setRegenerating] = useState(false);
  const [deleteContactId, setDeleteContactId] = useState<string | null>(null);
  const [deletingContact, setDeletingContact] = useState(false);
  const [setupRunning, setSetupRunning] = useState(false);
  const [setupStep, setSetupStep] = useState<string | null>(null);
  const [selectedContactId, setSelectedContactId] = useState<string>("");
  const [activeTab, setActiveTab] = useState("company");
  const [addContactOpen, setAddContactOpen] = useState(false);
  const [newContact, setNewContact] = useState({ name: "", title: "", email: "", linkedin: "" });
  const [savingContact, setSavingContact] = useState(false);
  const [syncingFathom, setSyncingFathom] = useState(false);
  const [analyzingMeeting, setAnalyzingMeeting] = useState<string | null>(null);
  const [generatingContactId, setGeneratingContactId] = useState<string | null>(null);
  const [regeneratingSection, setRegeneratingSection] = useState<string | null>(null);
  const [editingContactId, setEditingContactId] = useState<string | null>(null);
  const [editRoleFocus, setEditRoleFocus] = useState("");
  const [editUserNotes, setEditUserNotes] = useState("");
  // extractingProfiles state removed — extraction is now part of the generate pipeline

  // Auto-generate AI summary for creator contacts on load (every time contacts change)
  const autoGeneratedRef = useRef<Set<string>>(new Set());
  const setupRanRef = useRef(false);
  useEffect(() => {
    if (!id || contacts.length === 0) return;
    const creatorsWithoutProfile = contacts.filter((c: any) => {
      const hp = (c.hubspot_properties as any) || {};
      const isCreator = !!hp.first_tutorial_create_date;
      const hasProfile = !!(c as any).contact_profile?.account_narrative;
      return isCreator && !hasProfile && !autoGeneratedRef.current.has(c.id);
    });
    if (creatorsWithoutProfile.length === 0) return;

    // Mark all as queued so we don't re-trigger
    creatorsWithoutProfile.forEach((c: any) => autoGeneratedRef.current.add(c.id));

    const runExtraction = async () => {
      try {
        await supabase.functions.invoke("extract-contact-profile", { body: { company_id: id } });
        queryClient.invalidateQueries({ queryKey: ["contacts", id] });
      } catch (e) {
        console.warn("Auto profile extraction failed:", e);
      }
    };
    runExtraction();
  }, [id, contacts, queryClient]);


  useEffect(() => {
    if (contacts.length > 0 && activeTab === "company") {
      setActiveTab("contacts");
    }
  }, [contacts.length, activeTab]);

  const effectiveContactId = selectedContactId || contacts[0]?.id || "";
  const { data: companyCards, isLoading: cardsLoading } = useCompanyCards(id, effectiveContactId || undefined);

  const regenerateSection = useCallback(async (section: "contacts" | "strategy" | "outreach" | "story" | "signals" | "company") => {
    if (!id) return;
    setRegeneratingSection(section);
    try {
      if (section === "contacts") {
        await supabase.functions.invoke("find-contacts", { body: { company_id: id } });
        queryClient.invalidateQueries({ queryKey: ["contacts", id] });
      } else if (section === "signals") {
        await supabase.functions.invoke("run-signals", { body: { company_id: id, mode: "full" } });
        queryClient.invalidateQueries({ queryKey: ["signals", id] });
        queryClient.invalidateQueries({ queryKey: ["snapshots", id] });
      } else {
        await supabase.functions.invoke("generate-cards", {
          body: { company_id: id, tab: section, contact_id: section !== "company" ? (effectiveContactId || undefined) : undefined },
        });
        queryClient.invalidateQueries({ queryKey: ["company_cards", id], exact: false });
      }
      toast.success(`${section} regenerated`);
    } catch (e: any) {
      toast.error(e.message || `Failed to regenerate ${section}`);
    } finally {
      setRegeneratingSection(null);
    }
  }, [id, effectiveContactId, queryClient]);

  const companyAny = company as any;
  const companyCategory = companyAny?.category || (companyAny?.source_type === "inbound" ? "business" : companyAny?.partner ? "partner" : "business");
  const isPartnerCategory = companyCategory === "partner";

  const handleAddContact = async () => {
    if (!id || !newContact.name.trim()) return;
    setSavingContact(true);
    const missingContactInfo = !newContact.email.trim() || !newContact.linkedin.trim();
    try {
      // First insert the contact manually
      const { data: inserted, error } = await supabase.from("contacts").insert({
        company_id: id, name: newContact.name.trim(),
        title: newContact.title.trim() || null, email: newContact.email.trim() || null,
        linkedin: newContact.linkedin.trim() || null, source: "manual",
      }).select("id").single();
      if (error) throw error;

      // If email and linkedin are both blank, call Apollo to enrich
      if (missingContactInfo) {
        toast.info("Looking up contact details via Apollo…");
        try {
          const { data: apolloData, error: fnErr } = await supabase.functions.invoke("find-contacts", {
            body: { company_id: id, name_hint: newContact.name.trim() },
          });
          if (fnErr) throw fnErr;
          // Apollo may have saved a contact — check if it enriched the one we just inserted
          const { data: enriched } = await supabase
            .from("contacts")
            .select("email, linkedin")
            .eq("id", inserted.id)
            .maybeSingle();
          if (enriched?.email || enriched?.linkedin) {
            toast.success("Contact added and enriched via Apollo");
          } else {
            toast.success(`Contact added — Apollo found ${apolloData?.contacts_found ?? 0} related contacts`);
          }
        } catch {
          toast.success("Contact added (Apollo enrichment unavailable)");
        }
      } else {
        toast.success("Contact added");
      }

      setNewContact({ name: "", title: "", email: "", linkedin: "" });
      setAddContactOpen(false);
      queryClient.invalidateQueries({ queryKey: ["contacts", id] });
    } catch (e: any) { toast.error(e.message || "Failed to add contact"); }
    finally { setSavingContact(false); }
  };

  const handleDeleteContact = async (contactId: string) => {
    setDeletingContact(true);
    try {
      const { error } = await supabase.from("contacts").delete().eq("id", contactId);
      if (error) throw error;
      toast.success("Contact deleted");
      setDeleteContactId(null);
      queryClient.invalidateQueries({ queryKey: ["contacts", id] });
    } catch (e: any) { toast.error(e.message || "Failed to delete contact"); }
    finally { setDeletingContact(false); }
  };

  const regenerate = async (mode: string = "full") => {
    if (!id) return;
    setRegenerating(true);
    try {
      // Step 1: Run signals
      toast.info("Step 1/2 — Running signal search…");
      const { data, error } = await supabase.functions.invoke("run-signals", { body: { company_id: id, mode } });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      toast.success(`Signals complete — ${data?.signals_found ?? 0} found for ${data?.company || "company"}`);

      // Step 2: Sync Fathom meetings (if company has a domain)
      if (companyAny?.domain) {
        toast.info("Syncing Fathom meetings…");
        try {
          const { data: fData, error: fErr } = await supabase.functions.invoke("sync-fathom", {
            body: { domain: companyAny.domain, company_id: id },
          });
          if (!fErr && !fData?.error) {
            toast.success(`Fathom synced — ${fData?.meetings_synced ?? 0} meetings`);
            queryClient.invalidateQueries({ queryKey: ["meetings", id] });
          }
        } catch (fe: any) {
          console.warn("Fathom sync non-fatal:", fe.message);
        }
      }

      // Step 3: Find contacts via Apollo (skip for partner companies — contacts come from HubSpot)
      if (companyAny?.category === "partner" || (!companyAny?.category && companyAny?.source_type !== "inbound")) {
        toast.info("Step 3/3 — Finding contacts via Apollo…");
        try {
          const { data: contactData, error: contactErr } = await supabase.functions.invoke("find-contacts", { body: { company_id: id } });
          if (contactErr) throw contactErr;
          if (contactData?.error) throw new Error(contactData.error);
          if (contactData?.contacts_found > 0) {
            toast.success(`Found ${contactData.contacts_found} contacts via Apollo`);
          } else {
            toast.warning("No contacts found — check company domain is correct");
          }
        } catch (ce: any) {
          console.error("Contact enrichment failed:", ce);
          toast.error("Contact enrichment failed: " + (ce.message || "Unknown error"));
        } finally {
        }
      }

      // Step 3: For non-partner companies, extract contact profiles and generate company cards
      if (companyAny?.category !== "partner") {
        // Extract AI profiles from HubSpot data
        toast.info("Extracting contact profiles…");
        try {
          const { data: profileData, error: profileErr } = await supabase.functions.invoke("extract-contact-profile", { body: { company_id: id } });
          if (profileErr) console.warn("Profile extraction failed:", profileErr);
          else if (profileData?.profiles_extracted > 0) toast.success(`Extracted ${profileData.profiles_extracted} AI profiles`);
        } catch (pe: any) { console.warn("Profile extraction error:", pe.message); }

        // Generate company intel cards
        toast.info("Generating company intel…");
        try {
          const { data: cardData, error: cardErr } = await supabase.functions.invoke("generate-cards", { body: { company_id: id, tab: "company" } });
          if (cardErr) throw cardErr;
          if (cardData?.error) throw new Error(cardData.error);
          toast.success("Company intel generated");
        } catch (ce: any) {
          console.error("Card generation failed:", ce);
          toast.error("Card generation failed: " + (ce.message || "Unknown error"));
        }
      }

      queryClient.invalidateQueries({ queryKey: ["company", id] });
      queryClient.invalidateQueries({ queryKey: ["signals", id] });
      queryClient.invalidateQueries({ queryKey: ["snapshots", id] });
      queryClient.invalidateQueries({ queryKey: ["contacts", id] });
      // REFACTOR: (b) contact-scoped — prefix invalidation intentionally matches all ["company_cards", id, contactId] variants.
      queryClient.invalidateQueries({ queryKey: ["company_cards", id], exact: false });
      queryClient.invalidateQueries({ queryKey: ["companies"] });
    } catch (e: any) { toast.error(e.message || "Operation failed"); }
    finally { setRegenerating(false); }
  };

  const syncFathom = async () => {
    if (!company?.domain) { toast.error("Company needs a domain to sync Fathom meetings"); return; }
    setSyncingFathom(true);
    toast.info(`Syncing Fathom meetings for ${company.domain}…`);
    try {
      const { data, error } = await supabase.functions.invoke("sync-fathom", {
        body: { domain: company.domain, company_id: id },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      const synced = data.meetings_synced || 0;
      toast.success(`Synced ${synced} meetings`);
      await queryClient.invalidateQueries({ queryKey: ["meetings", id] });

      // Auto-analyze: get meetings with transcripts but no analysis yet
      if (synced > 0) {
        toast.info("Auto-analyzing transcripts…");
        const { data: freshMeetings } = await supabase
          .from("meetings")
          .select("id, transcript, transcript_analysis")
          .eq("company_id", id!)
          .not("transcript", "is", null)
          .is("transcript_analysis", null);

        if (freshMeetings && freshMeetings.length > 0) {
          for (const m of freshMeetings) {
            setAnalyzingMeeting(m.id);
            try {
              const { data: aData, error: aErr } = await supabase.functions.invoke("analyze-transcript", {
                body: { meeting_id: m.id },
              });
              if (aErr) throw aErr;
              if (aData?.error) throw new Error(aData.error);
            } catch (ae: any) {
              console.error(`Analysis failed for meeting ${m.id}:`, ae);
              toast.error(`Analysis failed for a meeting: ${ae.message}`);
            }
          }
          setAnalyzingMeeting(null);
          toast.success("Transcript analysis complete — check the Onboarding tab");
          queryClient.invalidateQueries({ queryKey: ["meetings", id] });
          setActiveTab("company");
        }
      }
    } catch (e: any) { toast.error(e.message || "Fathom sync failed"); }
    finally { setSyncingFathom(false); setAnalyzingMeeting(null); }
  };

  const analyzeTranscript = async (meetingId: string) => {
    setAnalyzingMeeting(meetingId);
    toast.info("Analyzing transcript…");
    try {
      const { data, error } = await supabase.functions.invoke("analyze-transcript", {
        body: { meeting_id: meetingId },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      toast.success("Transcript analysis complete");
      queryClient.invalidateQueries({ queryKey: ["meetings", id] });
    } catch (e: any) { toast.error(e.message || "Analysis failed"); }
    finally { setAnalyzingMeeting(null); }
  };

  const runCompanySetup = async () => {
    if (!id || setupRunning || setupRanRef.current) return;
    setupRanRef.current = true;
    setSetupRunning(true);
    try {
      if (isPartnerCategory) {
        setSetupStep("Searching for signals…");
        try {
          await supabase.functions.invoke("run-signals", {
            body: { company_id: id, mode: "full" },
          });
          queryClient.invalidateQueries({ queryKey: ["signals", id] });
          queryClient.invalidateQueries({ queryKey: ["snapshots", id] });
        } catch (e: any) {
          console.warn("Signals non-fatal:", e.message);
        }
      }

      if (companyAny?.domain) {
        setSetupStep("Syncing meetings…");
        try {
          await supabase.functions.invoke("sync-fathom", {
            body: { domain: companyAny.domain, company_id: id },
          });
          queryClient.invalidateQueries({ queryKey: ["meetings", id] });
        } catch (e: any) {
          console.warn("Fathom non-fatal:", e.message);
        }
      }

      if (isPartnerCategory) {
        setSetupStep("Finding contacts…");
        try {
          await supabase.functions.invoke("find-contacts", { body: { company_id: id } });
          queryClient.invalidateQueries({ queryKey: ["contacts", id] });
        } catch (e: any) {
          console.warn("Contacts non-fatal:", e.message);
        }
      }

      setSetupStep("Analyzing company…");
      try {
        await supabase.functions.invoke("generate-cards", {
          body: { company_id: id, tab: "company" },
        });
        queryClient.invalidateQueries({ queryKey: ["company_cards", id], exact: false });
      } catch (e: any) {
        console.warn("Company intel non-fatal:", e.message);
      }

      if (companyAny?.domain) {
        try {
          const { data: freshMeetings } = await supabase
            .from("meetings")
            .select("id, transcript, transcript_analysis")
            .eq("company_id", id)
            .not("transcript", "is", null)
            .is("transcript_analysis", null);
          if (freshMeetings && freshMeetings.length > 0) {
            setSetupStep("Analyzing transcripts…");
            for (const m of freshMeetings) {
              try {
                await supabase.functions.invoke("analyze-transcript", { body: { meeting_id: m.id } });
              } catch {}
            }
            queryClient.invalidateQueries({ queryKey: ["meetings", id] });
          }
        } catch {}
      }

      setSetupStep("Building contact profiles…");
      try {
        await supabase.functions.invoke("extract-contact-profile", { body: { company_id: id } });
        queryClient.invalidateQueries({ queryKey: ["contacts", id] });
      } catch (e: any) {
        console.warn("Profile extraction non-fatal:", e.message);
      }

      await updateCompany.mutateAsync({
        id: id!,
        updates: { last_processed_at: new Date().toISOString() },
      });
      queryClient.invalidateQueries({ queryKey: ["company", id] });
    } catch (e: any) {
      console.error("Company setup failed:", e.message);
      toast.error("Setup failed — try refreshing");
      setupRanRef.current = false;
    } finally {
      setSetupRunning(false);
      setSetupStep(null);
    }
  };

  useEffect(() => {
    if (!company || isLoading) return;
    const needsSetup = !companyAny?.last_processed_at;
    if (needsSetup && !setupRunning && !setupRanRef.current) {
      runCompanySetup();
    }
  }, [company, isLoading]);

  const generateForContact = async (contactId: string) => {
    if (!id) return;
    setGeneratingContactId(contactId);
    try {
      // Step 1: Extract profile for this contact
      toast.info("Extracting contact profile…");
      try {
        await supabase.functions.invoke("extract-contact-profile", { body: { company_id: id, contact_id: contactId } });
        queryClient.invalidateQueries({ queryKey: ["contacts", id] });
      } catch (pe: any) { console.warn("Profile extraction non-fatal:", pe.message); }

      // Step 2: Generate contact-scoped tabs for this contact (in parallel)
      toast.info("Generating contact content…");

      const contactTabs = ["strategy", "outreach", "story"];
      const results = await Promise.allSettled(
        contactTabs.map((tab) =>
          supabase.functions.invoke("generate-cards", {
            body: { company_id: id, tab, contact_id: contactId },
          })
        )
      );

      const failures = results
        .map((result, i) => ({ result, tab: contactTabs[i] }))
        .filter(
          (r) =>
            r.result.status === "rejected" ||
            (r.result.status === "fulfilled" && (r.result.value.error || r.result.value.data?.error))
        );

      if (failures.length > 0) {
        const failedTabs = failures.map((f) => f.tab).join(", ");
        toast.warning(`Some tabs failed: ${failedTabs}. Others succeeded.`);
      }

      const firstName = contacts.find((c: any) => c.id === contactId)?.name?.split(" ")[0] || "contact";
      const slug = firstName.toLowerCase().replace(/[^a-z]/g, "");
      const storyUrl = !isPartnerCategory
        ? `/stories/${companyNameSlug}/${slug}`
        : company.partner
          ? `/${company.partner}/${companyNameSlug}/stories/${slug}`
          : null;
      toast.success(`Content generated for ${firstName}`, {
        action: storyUrl ? {
          label: "View Story →",
          onClick: () => window.open(storyUrl, "_blank"),
        } : undefined,
        duration: 8000,
      });
      // REFACTOR: (b) contact-scoped — prefix invalidation intentionally matches all ["company_cards", id, contactId] variants.
      queryClient.invalidateQueries({ queryKey: ["company_cards", id], exact: false });
      queryClient.invalidateQueries({ queryKey: ["contacts", id] });
      // Switch to this contact
      setSelectedContactId(contactId);
    } catch (e: any) { toast.error(e.message || "Generation failed"); }
    finally { setGeneratingContactId(null); }
  };

  if (isLoading) {
    return <div className="flex items-center justify-center py-20"><Loader2 className="w-6 h-6 animate-spin text-primary" /></div>;
  }

  if (!company) {
    return (
      <div className="text-center py-20">
        <h2 className="text-xl font-bold">Company not found</h2>
        <Link to="/" className="text-primary text-sm mt-2 inline-block">← Back to Dashboard</Link>
      </div>
    );
  }

  const latestSnapshot = snapshots[0];
  const snap = latestSnapshot ? parseJson<SnapshotJSON>(latestSnapshot.snapshot_json) : null;

  const companyStage = companyAny?.stage || "prospect";
  const companyNameSlug = company.name.toLowerCase().replace(/\s+/g, "-");

  const accountData = parseJson<{
    name?: string; about?: { text?: string; status?: string };
    industry?: { value?: string; status?: string };
    employees?: { value?: string; status?: string };
    hq?: { value?: string; status?: string };
    revenue_range?: { value?: string; status?: string };
    products_services?: { name: string; status?: string }[];
  }>(companyCards?.account_json as Json);

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <Link to="/" className="text-foreground/45 hover:text-foreground transition-colors"><ArrowLeft className="w-5 h-5" /></Link>
          <div>
            <h1 className="text-display font-bold tracking-tight leading-tight">{company.name}</h1>
          </div>
        </div>
      </div>

      {setupRunning && (
        <div className="flex items-center gap-3 px-4 py-3 rounded-lg bg-primary/[0.06] border border-primary/10">
          <Loader2 className="w-4 h-4 animate-spin text-primary flex-shrink-0" />
          <div>
            <div className="text-body font-medium text-foreground">Setting up {company.name}…</div>
            {setupStep && <div className="text-caption text-foreground/45 mt-0.5">{setupStep}</div>}
          </div>
        </div>
      )}

      <Tabs defaultValue={contacts.length > 0 ? "contacts" : "company"} className="w-full" onValueChange={setActiveTab}>
        <div className="flex items-center justify-between gap-3 mb-4">
          <TabsList>
            <TabsTrigger value="company" className="text-sm">Company</TabsTrigger>
            <TabsTrigger value="contacts" className="text-sm">
              Contacts
              {contacts.length > 0 && (
                <span className="ml-1.5 text-micro text-foreground/25 tabular-nums">{contacts.length}</span>
              )}
            </TabsTrigger>
          </TabsList>

        </div>

        {/* ============ TAB 1: COMPANY ============ */}
        <TabsContent value="company" className="space-y-8 mt-6">
          <div className="flex items-center justify-between gap-3 pb-6">
            <div className="flex items-center gap-2 flex-wrap text-caption text-foreground/45">
              {company.domain && <span>{company.domain}</span>}
              {company.domain && <span className="text-foreground/15">·</span>}
              <Select
                value={companyCategory}
                onValueChange={async (val) => {
                  await updateCompany.mutateAsync({ id: id!, updates: { category: val } as any });
                  queryClient.invalidateQueries({ queryKey: ["company", id] });
                }}
              >
                <SelectTrigger className="h-6 text-micro w-auto border-0 bg-transparent p-0 gap-1 text-foreground/45 hover:text-foreground [&>svg]:w-3 [&>svg]:h-3">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="school">School</SelectItem>
                  <SelectItem value="business">Business</SelectItem>
                  <SelectItem value="partner">Partner</SelectItem>
                </SelectContent>
              </Select>
              <span className="text-foreground/15">·</span>
              <Select
                value={companyStage}
                onValueChange={async (val) => {
                  await updateCompany.mutateAsync({ id: id!, updates: { stage: val } as any });
                  queryClient.invalidateQueries({ queryKey: ["company", id] });
                }}
              >
                <SelectTrigger className="h-6 text-micro w-auto border-0 bg-transparent p-0 gap-1 text-foreground/45 hover:text-foreground [&>svg]:w-3 [&>svg]:h-3">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="prospect">Prospect</SelectItem>
                  <SelectItem value="active_opp">Active Opp</SelectItem>
                  <SelectItem value="customer">Customer</SelectItem>
                  <SelectItem value="expansion">Expansion</SelectItem>
                </SelectContent>
              </Select>
              {company.scout_score != null && (
                <>
                  <span className="text-foreground/15">·</span>
                  <ScoreCell score={company.scout_score} size="sm" />
                </>
              )}
            </div>
            <Button
              size="sm"
              variant="ghost"
              className="h-7 px-2 text-micro gap-1 text-foreground/25 hover:text-foreground"
              onClick={() => { setupRanRef.current = false; runCompanySetup(); }}
              disabled={setupRunning}
            >
              {setupRunning
                ? <Loader2 className="w-3 h-3 animate-spin" />
                : <RefreshCw className="w-3 h-3" />}
              Refresh
            </Button>
          </div>

          {/* Company profile — flat, no cards */}
          <div className="space-y-3">
            {accountData?.about?.text && (
              <p className="text-body text-foreground/65 leading-relaxed max-w-2xl">
                {accountData.about.text}
              </p>
            )}
            {company.scout_summary && (
              <p className="text-caption text-foreground/45 leading-relaxed max-w-2xl italic">
                {company.scout_summary}
              </p>
            )}
            <div className="flex flex-wrap gap-x-6 gap-y-1 text-caption">
              {(accountData?.industry?.value || company.industry) && (
                <span className="text-foreground/45">
                  <span className="text-foreground/25">Industry</span>{" "}
                  <span className="text-foreground/65">{accountData?.industry?.value || company.industry?.replace(/_/g, " ")}</span>
                </span>
              )}
              {(accountData?.employees?.value || company.headcount) && (
                <span className="text-foreground/45">
                  <span className="text-foreground/25">Employees</span>{" "}
                  <span className="text-foreground/65">{accountData?.employees?.value || `${company.headcount?.toLocaleString()}+`}</span>
                </span>
              )}
              {accountData?.revenue_range?.value && accountData.revenue_range.value !== "Unknown" && (
                <span className="text-foreground/45">
                  <span className="text-foreground/25">Revenue</span>{" "}
                  <span className="text-foreground/65">{accountData.revenue_range.value}</span>
                </span>
              )}
              {company.partner && (
                <span className="text-foreground/45">
                  <span className="text-foreground/25">Partner</span>{" "}
                  <span className="text-foreground/65">{company.partner}</span>
                </span>
              )}
              {company.hq_country && (
                <span className="text-foreground/45">
                  <span className="text-foreground/25">HQ</span>{" "}
                  <span className="text-foreground/65">{company.hq_country}</span>
                </span>
              )}
            </div>
          </div>

          {/* HubSpot Product Properties */}
          {companyAny?.hubspot_properties && Object.keys(companyAny.hubspot_properties).length > 0 && (
            <Collapsible>
              <CollapsibleTrigger className="flex items-center gap-2 w-full text-left">
                <ChevronRight className="w-4 h-4 text-foreground/45 transition-transform data-[state=open]:rotate-90" />
                <span className="section-label">iorad Product Data (HubSpot)</span>
                <Badge variant="outline" className="text-micro h-4 ml-auto">
                  {Object.entries(companyAny.hubspot_properties).filter(([_, v]) => v !== null && v !== "" && v !== undefined).length} properties
                </Badge>
              </CollapsibleTrigger>
              <CollapsibleContent className="mt-3">
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2">
                  {Object.entries(companyAny.hubspot_properties as Record<string, any>)
                    .filter(([_, v]) => v !== null && v !== "" && v !== undefined)
                    .filter(([k]) => !["name", "domain", "industry", "country", "numberofemployees", "hs_object_id", "createdate", "hs_lastmodifieddate", "hs_pipeline"].includes(k))
                    .sort(([a], [b]) => a.localeCompare(b))
                    .map(([key, value]) => (
                       <div key={key} className="px-3 py-2 rounded-lg border border-border/30 bg-secondary/20">
                        <div className="section-label truncate" title={key}>
                          {key.replace(/_/g, " ").replace(/^hs /, "")}
                        </div>
                        <div className="text-caption font-medium text-foreground mt-0.5 truncate" title={String(value)}>
                          {String(value).length > 80 ? String(value).slice(0, 80) + "…" : String(value)}
                        </div>
                      </div>
                    ))}
                </div>
              </CollapsibleContent>
            </Collapsible>
          )}

          {/* Meetings (Fathom) */}
          <div className="flex items-center justify-between py-3 border-t border-border/20">
            <span className="text-caption text-foreground/45">
              {meetings.length} meeting{meetings.length !== 1 ? "s" : ""} synced
              {meetings.filter((m: any) => m.transcript_analysis).length > 0 && (
                <span> · {meetings.filter((m: any) => m.transcript_analysis).length} analyzed</span>
              )}
            </span>
            <button
              onClick={syncFathom}
              disabled={syncingFathom || !!analyzingMeeting}
              className="text-micro text-primary hover:text-primary/80 font-medium disabled:opacity-40"
            >
              {syncingFathom ? "Syncing…" : "Sync Fathom"}
            </button>
          </div>

          {snap && latestSnapshot && (
            <div className="panel">
              <div className="panel-header flex items-center justify-between">
                <span>iorad Expansion Analysis</span>
                <span className="text-micro text-foreground/45 normal-case tracking-normal">
                  {latestSnapshot.model_version} · {latestSnapshot.prompt_version} · {new Date(latestSnapshot.created_at).toLocaleDateString()}
                </span>
              </div>

              {snap.why_now && toArray(snap.why_now).length > 0 && (
                <div className="mb-4 bg-primary/5 border border-primary/20 rounded-lg p-4">
                  <div className="section-label text-primary mb-2">Why Now</div>
                  {toArray(snap.why_now).map((item, i) => <p key={i} className="text-body text-foreground/65 leading-relaxed">{item}</p>)}
                </div>
              )}

              <Accordion type="multiple" defaultValue={["executive-narrative"]} className="space-y-2">
                {snap.signal_deconstruction && (
                  <AccordionItem value="signal-deconstruction" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><Target className="w-4 h-4 text-primary" /> Signal Deconstruction</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <div className="space-y-4">
                        {snap.signal_deconstruction.company_stage && (
                          <div>
                            <div className="text-micro text-foreground/45 mb-1">Company Stage</div>
                            <span className="text-sm bg-primary/10 text-primary px-2 py-0.5 rounded">{snap.signal_deconstruction.company_stage}</span>
                          </div>
                        )}
                        {snap.signal_deconstruction.observable_facts?.length ? (
                          <div>
                            <div className="text-micro text-foreground/45 mb-2">Observable Facts</div>
                            <ul className="space-y-1">{snap.signal_deconstruction.observable_facts.map((f, i) => <li key={i} className="text-sm flex items-start gap-2"><span className="text-primary">•</span>{f}</li>)}</ul>
                          </div>
                        ) : null}
                        {snap.signal_deconstruction.workflow_stress_indicators?.length ? (
                          <div>
                            <div className="text-micro text-foreground/45 mb-2">Workflow Stress Indicators</div>
                            <ul className="space-y-1">{snap.signal_deconstruction.workflow_stress_indicators.map((w, i) => <li key={i} className="text-sm flex items-start gap-2"><AlertCircle className="w-3.5 h-3.5 text-destructive mt-0.5 flex-shrink-0" />{w}</li>)}</ul>
                          </div>
                        ) : null}
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                )}

                {snap.operational_friction?.length ? (
                  <AccordionItem value="operational-friction" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><Zap className="w-4 h-4 text-primary" /> Operational Friction</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <div className="space-y-3">
                        {snap.operational_friction.map((f, i) => (
                          <div key={i} className="bg-secondary/50 rounded-lg p-4 space-y-1">
                            <div className="text-body"><span className="font-medium text-foreground">Cause:</span> <span className="text-foreground/65">{f.cause}</span></div>
                            <div className="text-body"><span className="font-medium text-foreground">→ Effect:</span> <span className="text-foreground/65">{f.effect}</span></div>
                            <div className="text-body"><span className="font-medium text-foreground">→ Bottleneck:</span> <span className="text-foreground/65">{f.bottleneck}</span></div>
                          </div>
                        ))}
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                ) : null}

                {snap.partner_platform_ceiling && (
                  <AccordionItem value="partner-ceiling" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><TrendingUp className="w-4 h-4 text-primary" /> Partner Platform Ceiling</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <div className="space-y-4">
                        {snap.partner_platform_ceiling.platform_strengths?.length ? (
                          <div>
                            <div className="text-micro text-foreground/45 mb-2">Platform Strengths</div>
                            <div className="flex flex-wrap gap-1.5">{snap.partner_platform_ceiling.platform_strengths.map((s, i) => <span key={i} className="text-xs bg-primary/10 text-primary px-2 py-0.5 rounded">{s}</span>)}</div>
                          </div>
                        ) : null}
                        {snap.partner_platform_ceiling.execution_gaps?.length ? (
                          <div>
                            <div className="text-micro text-foreground/45 mb-2">Execution Gaps</div>
                            <ul className="space-y-1">{snap.partner_platform_ceiling.execution_gaps.map((g, i) => <li key={i} className="text-sm flex items-start gap-2"><span className="text-destructive">✕</span>{g}</li>)}</ul>
                          </div>
                        ) : null}
                        {snap.partner_platform_ceiling.key_insight && (
                          <div className="bg-primary/5 border border-primary/20 rounded p-4 text-body italic text-foreground/65">{snap.partner_platform_ceiling.key_insight}</div>
                        )}
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                )}

                {snap.embedded_leverage && (
                  <AccordionItem value="embedded-leverage" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><Zap className="w-4 h-4 text-primary" /> Embedded iorad Leverage</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        {(["situation", "constraint", "intervention", "transformation"] as const).map(key => {
                          const val = snap.embedded_leverage?.[key];
                          if (!val) return null;
                          const labels: Record<string, string> = { situation: "Situation", constraint: "Constraint", intervention: "Intervention", transformation: "Transformation" };
                          return (
                            <div key={key} className="bg-secondary/50 rounded-lg p-4">
                              <div className="text-micro text-foreground/45 mb-1">{labels[key]}</div>
                              <p className="text-sm text-foreground/90">{val}</p>
                            </div>
                          );
                        })}
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                )}

                {snap.quantified_impact?.length ? (
                  <AccordionItem value="quantified-impact" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><BarChart3 className="w-4 h-4 text-primary" /> Quantified Impact</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <div className="space-y-3">
                        {snap.quantified_impact.map((q, i) => (
                          <div key={i} className="border rounded-lg p-4 space-y-2">
                            <div className="font-medium text-sm text-foreground">{q.metric}</div>
                            <div className="text-micro text-foreground/45"><span className="font-mono">Assumptions:</span> {q.assumptions}</div>
                            <div className="text-xs font-mono bg-secondary/50 rounded p-2 text-foreground/80">{q.calculation}</div>
                            <div className="text-sm font-bold text-primary">{q.result}</div>
                          </div>
                        ))}
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                ) : null}

                {snap.executive_narrative && (
                  <AccordionItem value="executive-narrative" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><FileText className="w-4 h-4 text-primary" /> Executive Narrative</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <div className="prose prose-sm dark:prose-invert max-w-none">
                        {(Array.isArray(snap.executive_narrative)
                          ? snap.executive_narrative
                          : typeof snap.executive_narrative === 'string' ? snap.executive_narrative.split("\n\n") : []
                        ).map((p: string, i: number) => (
                          <p key={i} className="text-body text-foreground/65 leading-relaxed mb-4">{p}</p>
                        ))}
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                )}

                {snap.outbound_positioning && (
                  <AccordionItem value="outbound-positioning" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><MessageSquareQuote className="w-4 h-4 text-primary" /> Outbound Positioning</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <div className="space-y-3">
                        {snap.outbound_positioning.executive_framing && (
                          <div className="border-l border-primary/20 pl-3">
                            <div className="text-micro text-foreground/45 mb-1">Executive Framing</div>
                            <p className="text-sm text-foreground/90 italic">"{snap.outbound_positioning.executive_framing}"</p>
                          </div>
                        )}
                        {snap.outbound_positioning.efficiency_framing && (
                          <div className="border-l border-primary/20 pl-3">
                            <div className="text-micro text-foreground/45 mb-1">Efficiency / Revenue</div>
                            <p className="text-sm text-foreground/90 italic">"{snap.outbound_positioning.efficiency_framing}"</p>
                          </div>
                        )}
                        {snap.outbound_positioning.risk_framing && (
                          <div className="border-l border-primary/20 pl-3">
                            <div className="text-micro text-foreground/45 mb-1">Risk Mitigation</div>
                            <p className="text-sm text-foreground/90 italic">"{snap.outbound_positioning.risk_framing}"</p>
                          </div>
                        )}
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                )}

                {snap.competitive_insulation?.length ? (
                  <AccordionItem value="competitive-insulation" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><Shield className="w-4 h-4 text-primary" /> Competitive Insulation</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <ul className="space-y-1.5">{snap.competitive_insulation.map((r, i) => <li key={i} className="text-sm flex items-start gap-2"><CheckCircle2 className="w-3.5 h-3.5 text-primary mt-0.5 flex-shrink-0" />{r}</li>)}</ul>
                    </AccordionContent>
                  </AccordionItem>
                ) : null}

                {snap.evidence?.length ? (
                  <AccordionItem value="evidence" className="border rounded-lg px-4">
                    <AccordionTrigger className="text-body font-medium">
                      <div className="flex items-center gap-2"><ExternalLink className="w-4 h-4 text-primary" /> Cited Evidence ({snap.evidence.length})</div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <div className="space-y-2">
                        {snap.evidence.map((ev, i) => (
                          <div key={i} className="text-xs border-l border-primary/20 pl-3 py-1">
                            <p className="text-foreground/65 italic">"{ev.snippet || ev.detail || ""}"</p>
                            <a href={ev.source_url || ev.url || "#"} target="_blank" rel="noopener noreferrer" className="text-primary hover:underline flex items-center gap-1 mt-0.5">
                              <ExternalLink className="w-3 h-3" /> {ev.source_type || ev.signal_type || "source"} · {ev.date || "no date"}
                            </a>
                          </div>
                        ))}
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                ) : null}
              </Accordion>
            </div>
          )}


          <Collapsible>
            <CollapsibleTrigger className="flex items-center justify-between w-full py-3">
              <h3 className="text-body font-medium">Onboarding</h3>
              <ChevronRight className="w-4 h-4 text-foreground/25 transition-transform data-[state=open]:rotate-90" />
            </CollapsibleTrigger>
            <CollapsibleContent>
              <OnboardingTab
                meetings={meetings}
                analyzingMeeting={analyzingMeeting}
                onAnalyze={analyzeTranscript}
              />
            </CollapsibleContent>
          </Collapsible>

          <CompanySignalsSection
            signals={signals}
            snapshots={snapshots}
            activityEvents={activityEvents}
            meetings={meetings}
            company={company}
          />
        </TabsContent>

        <TabsContent value="contacts" className="mt-6">
          <ContactDetailView
            companyId={id!}
            company={company}
            companyNameSlug={companyNameSlug}
            isPartnerCategory={isPartnerCategory}
            contacts={contacts}
            selectedContactId={selectedContactId || contacts[0]?.id || ""}
            onSelectContact={setSelectedContactId}
            editingContactId={editingContactId}
            editRoleFocus={editRoleFocus}
            editUserNotes={editUserNotes}
            onSetEditingContactId={setEditingContactId}
            onSetEditRoleFocus={setEditRoleFocus}
            onSetEditUserNotes={setEditUserNotes}
            addContactOpen={addContactOpen}
            onSetAddContactOpen={setAddContactOpen}
            newContact={newContact}
            onSetNewContact={setNewContact}
            onAddContact={handleAddContact}
            savingContact={savingContact}
            deleteContactId={deleteContactId}
            onSetDeleteContactId={setDeleteContactId}
            deletingContact={deletingContact}
            onConfirmDelete={() => deleteContactId && handleDeleteContact(deleteContactId)}
            generatingContactId={generatingContactId}
            onGenerateForContact={generateForContact}
            setupRunning={setupRunning}
            companyCards={companyCards}
            cardsLoading={cardsLoading}
            regeneratingSection={regeneratingSection}
            onRegenerateSection={(section) => regenerateSection(section as any)}
          />
        </TabsContent>

      </Tabs>
    </div>
  );
}
